/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InquiryService } from "../inquiry.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InquiryCreateInput } from "./InquiryCreateInput";
import { Inquiry } from "./Inquiry";
import { InquiryFindManyArgs } from "./InquiryFindManyArgs";
import { InquiryWhereUniqueInput } from "./InquiryWhereUniqueInput";
import { InquiryUpdateInput } from "./InquiryUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InquiryControllerBase {
  constructor(
    protected readonly service: InquiryService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Inquiry })
  @nestAccessControl.UseRoles({
    resource: "Inquiry",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createInquiry(
    @common.Body() data: InquiryCreateInput
  ): Promise<Inquiry> {
    return await this.service.createInquiry({
      data: {
        ...data,

        property: data.property
          ? {
              connect: data.property,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        message: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userContactInfo: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Inquiry] })
  @ApiNestedQuery(InquiryFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Inquiry",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async inquiries(@common.Req() request: Request): Promise<Inquiry[]> {
    const args = plainToClass(InquiryFindManyArgs, request.query);
    return this.service.inquiries({
      ...args,
      select: {
        createdAt: true,
        id: true,
        message: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userContactInfo: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Inquiry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Inquiry",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async inquiry(
    @common.Param() params: InquiryWhereUniqueInput
  ): Promise<Inquiry | null> {
    const result = await this.service.inquiry({
      where: params,
      select: {
        createdAt: true,
        id: true,
        message: true,

        property: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        userContactInfo: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Inquiry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Inquiry",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateInquiry(
    @common.Param() params: InquiryWhereUniqueInput,
    @common.Body() data: InquiryUpdateInput
  ): Promise<Inquiry | null> {
    try {
      return await this.service.updateInquiry({
        where: params,
        data: {
          ...data,

          property: data.property
            ? {
                connect: data.property,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          message: true,

          property: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          userContactInfo: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Inquiry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Inquiry",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteInquiry(
    @common.Param() params: InquiryWhereUniqueInput
  ): Promise<Inquiry | null> {
    try {
      return await this.service.deleteInquiry({
        where: params,
        select: {
          createdAt: true,
          id: true,
          message: true,

          property: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          userContactInfo: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
